### PR TITLE
fix(app): prevent accidental reassignment in request payloads

### PR DESCRIPTION
**Pull request by Karvel**
## Changes

  - [x] Create new `buildNestedRequestPayload()`.
  - [x] Move nested property logic.
  - [x] Add tests.
  - [x] Use `buildNestedRequestPayload()` when unpacking `dynamicContent`.
  - [x] Use `buildNestedRequestPayload()` when mapping from nested property to parent object (e.g. getting form values for role and agency from select fields).
  - [x] Fix breaking test in `LanguageStateService`.

## Purpose

Unpacking nested payloads should not be a side effect for `buildRequestPayload()`. It should be separated into its own method for clarity.

The current method can accidentally overwrite objects with nested values:

```ts
{
    id: 1,
    name: 'Test Tester',
    ...
    role: {
        id: 1,
        roleName: 'Admin'
    },
    agency: {
        id: 1,
        agencyName: 'TestCo'
    }
}
```

becomes

```ts
{
    id: 1,
    name: 'Test Tester',
    ...
    role: 1,
    agency: 'TestCo'
}
```

## Approach

_How does this change address the problem?_

## Pre-Testing TODOs

_What needs to be done before testing._

  1. Serve from the translation epic branch on the API.

#### If you are not a member of this project, _skip this step_

_How do the users test this change?_

  1. Login as an admin.
  2. Create a new user (this requires setting role and agency).
  3. Confirm that the values set correctly.
  4. Add a translation for an agent description value.
  5. Confirm that the values set correctly.

Closes #332.

### CODE REVIEW

**Review by michaelachrisco — APPROVED** [review]
Awesome that looks like a very interesting/frustrating bug. Nice job!

Couple of comments and one question on the actual `buildNestedRequestPayload`. No blockers that I can see.

**Review by pratimasakinala — APPROVED** [review]
Works great! Thanks for catching this bug.

**Review by DropsOfSerenity — COMMENTED** [review]
Others have reviewed already, I just wanted to make a comment on the tests.

**Review by mwallert — APPROVED** [review]
Other than the one comment, this looks good to me.

**Pull request merged**
